name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send API request to Supabase
        run: |
          curl -X GET "${{ secrets.https://lynuktgzmodaybofizsh.supabase.co }}/rest/v1/" \
          -H "apikey: ${{ secrets.sb_publishable_So1J_9qg2jABP4odsRKtYA_O_H7GF6k }}" \
          -H "Authorization: Bearer ${{ secrets.sb_publishable_So1J_9qg2jABP4odsRKtYA_O_H7GF6k }}" \
          -H "Content-Type: application/json"
